import "./globals.css";
import type { Metadata } from "next";

import ThemeProvider from "@/theme";
import { primaryFont } from "@/theme/typography";

import ProgressBar from "@/components/progress-bar";
import { MotionLazy } from "@/components/animate/motion-lazy";
import SnackbarProvider from "@/components/snackbar/snackbar-provider";
import { SettingsDrawer, SettingsProvider } from "@/components/settings";
import { LocalizationProvider } from "@/locales";
import { AuthProvider } from "@/auth/context/jwt";

// ----------------------------------------------------------------------

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={primaryFont.className}>
      <body>
        <AuthProvider>
          <LocalizationProvider>
            <SettingsProvider
              defaultSettings={{
                themeMode: "light", // 'light' | 'dark'
                themeDirection: "ltr", //  'rtl' | 'ltr'
                themeContrast: "default", // 'default' | 'bold'
                themeLayout: "vertical", // 'vertical' | 'horizontal' | 'mini'
                themeColorPresets: "default", // 'default' | 'cyan' | 'purple' | 'blue' | 'orange' | 'red'
                themeStretch: false,
              }}
            >
              <ThemeProvider>
                <MotionLazy>
                  <SnackbarProvider>
                    <SettingsDrawer />
                    <ProgressBar />
                    {children}
                  </SnackbarProvider>
                </MotionLazy>
              </ThemeProvider>
            </SettingsProvider>
          </LocalizationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
